version: "3"
services: 
  php:
    build: "./php/"
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    links: 
      - database:database
    depends_on: 
      - database
    
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: sina
      MYSQL_DATABASE: app
    volumes:
      - private_database_volume:/var/lib/mysql
  
  phpmyadmin_dasboard:
    image: phpmyadmin
    links: 
      - database:database
    ports:
      - 8080:80
    depends_on:
      - database
    environment:
      - PMA_HOST=database

volumes: 
  private_database_volume: