apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-lamp
spec:
  selector:
    matchLabels:
      app: docker-lamp
  replicas: 1
  template:
    metadata:
      labels:
        app: docker-lamp
    spec:
      containers:
      - name: docker-lamp
        image: sina-developer/docker-lamp:latest
        ports:
        - containerPort: 8080